const TAB_ICON_SIZE = 28;
const PRODUCT_CARD_BORDER_RADIUS = 12;
const ACTIVE_BUTTON_OPACITY = 0.5;
const HEADER_MAX_HEIGHT = 400;
const HEADER_MIN_HEIGHT = 110;
const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT;
export {
  TAB_ICON_SIZE,
  PRODUCT_CARD_BORDER_RADIUS,
  ACTIVE_BUTTON_OPACITY,
  HEADER_MAX_HEIGHT,
  HEADER_MIN_HEIGHT,
  HEADER_SCROLL_DISTANCE
};